version: '2'
services:
    webchat-app:
        image: webchat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://webchat-mysql:3306/webchat?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    webchat-mysql:
        extends:
            file: mysql.yml
            service: webchat-mysql
